# Generated by Django 2.2 on 2020-12-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='url')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('caption', models.CharField(max_length=200, null=True)),
                ('date_posted', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Galeri',
            },
        ),
    ]
