# Generated by Django 2.2 on 2020-12-25 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20201225_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='title',
            field=models.CharField(max_length=200, null=True, verbose_name='Judul'),
        ),
    ]
