# Generated by Django 2.2 on 2021-02-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20210105_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
