# Generated by Django 2.2 on 2020-12-10 13:56

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='url')),
                ('title', models.CharField(max_length=200, null=True)),
                ('article', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('date_posted', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'News',
            },
        ),
    ]
