# Generated by Django 2.2 on 2020-12-15 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0002_news_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'Kegiatan'},
        ),
    ]
