# Generated by Django 2.2 on 2020-12-24 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0003_auto_20201215_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/berita'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=200, null=True, verbose_name='Judul'),
        ),
    ]
