# Generated by Django 2.2 on 2020-12-24 22:48

import ckeditor_uploader.fields
from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('berita', '0004_auto_20201225_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='news',
            name='article',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Artikel'),
        ),
    ]
