# Generated by Django 2.2 on 2021-01-05 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0006_remove_news_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/berita'),
        ),
    ]
