# Generated by Django 2.2 on 2021-01-14 08:59

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0007_auto_20210105_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('image', models.ImageField(null=True, upload_to='uploads/berita')),
                ('title', models.CharField(max_length=200, null=True, verbose_name='Judul')),
                ('article', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Artikel')),
                ('date_posted', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Publikasi',
            },
        ),
    ]
