# Generated by Django 2.2 on 2021-01-22 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0008_publication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'Berita'},
        ),
    ]
