# Generated by Django 2.2 on 2020-12-10 12:15

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201210_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=0, size=[1200, 600], upload_to='carousel')),
                ('caption_image_1', models.CharField(max_length=200)),
                ('image2', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=0, size=[1200, 600], upload_to='carousel')),
                ('caption_image_2', models.CharField(max_length=200)),
                ('image3', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=0, size=[1200, 600], upload_to='carousel')),
                ('caption_image_3', models.CharField(max_length=200)),
                ('image4', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=0, size=[1200, 600], upload_to='carousel')),
                ('caption_image_4', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Carousel_1',
        ),
        migrations.DeleteModel(
            name='Carousel_2',
        ),
        migrations.DeleteModel(
            name='Carousel_3',
        ),
        migrations.DeleteModel(
            name='Carousel_4',
        ),
    ]
