# Generated by Django 2.2 on 2020-12-10 12:31

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201210_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='image1',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=0, size=[1200, 600], upload_to='carousel'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='image2',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=0, size=[1200, 600], upload_to='carousel'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='image3',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=0, size=[1200, 600], upload_to='carousel'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='image4',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=0, size=[1200, 600], upload_to='carousel'),
        ),
    ]
