# Generated by Django 2.2 on 2020-12-10 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20201210_2017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About'},
        ),
        migrations.AlterModelOptions(
            name='carousel',
            options={'verbose_name_plural': 'Carousel'},
        ),
    ]
