# Generated by Django 2.2 on 2020-12-25 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20201210_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('subject', models.CharField(max_length=500, null=True)),
                ('message', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Contact',
            },
        ),
    ]
