# Generated by Django 2.2 on 2020-12-30 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=200, null=True, verbose_name='Alamat e-mail'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(null=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=500, null=True, verbose_name='Nama'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=500, null=True, verbose_name='Subject'),
        ),
    ]
