# Generated by Django 2.2 on 2021-01-13 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20201230_0942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'Profile Kampoeng Cyber'},
        ),
    ]
