# Generated by Django 2.2 on 2021-01-13 06:04

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20210113_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Artikel')),
            ],
            options={
                'verbose_name_plural': 'Sejarah Kampoeng Cyber',
            },
        ),
    ]
